In [1]:
import numpy as np


In [4]:
arr1 = np.array([1,2,3,4])
print(arr1)



[1 2 3 4]


In [5]:
type(arr1)

numpy.ndarray

In [7]:
arr = np.zeros((2,3))

In [8]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr = np.ones((3,5))

In [10]:
arr


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
arr = np.arange(10)

In [12]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
for i in arr:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [15]:
arr = np.identity(4)

In [16]:
arr


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
arr = np.random.random((2,3))

In [19]:
arr

array([[0.26528554, 0.63631688, 0.21713113],
       [0.52954514, 0.61507411, 0.38370673]])

In [20]:
arr = np.linspace(-12,12,6)

In [21]:
arr


array([-12. ,  -7.2,  -2.4,   2.4,   7.2,  12. ])

In [22]:
arr2 = arr.copy()

In [23]:
arr2


array([-12. ,  -7.2,  -2.4,   2.4,   7.2,  12. ])

In [24]:
arr = np.identity(5)

In [25]:
arr.ndim

2

In [26]:
arr.shape

(5, 5)

In [27]:
arr.itemsize


8

In [28]:
arr.dtype


dtype('float64')

In [29]:
time.sleep(10)

NameError: name 'time' is not defined

In [30]:
import time

In [ ]:
time.sleep(10)
for i in range(100):
    keyboard.write("You are being spammed")
    keyboard.press_and_release('return')
    time.sleep(1)
    
    

In [32]:
l = list(range(100))

In [33]:
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [35]:
arr = np.arange(100)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
import sys

In [38]:
sys.getsize(arr)

AttributeError: module 'sys' has no attribute 'getsize'

In [39]:
arr.size*arr.itemsize

400

In [41]:
sys.getsizeof(l[1])*len(l)

2800

In [42]:
arr.max

<function ndarray.max>

In [43]:
arr.max()

99

In [44]:
arr.min()

0

In [45]:
arr.sum()

4950

In [46]:
arr.mean()

49.5

In [47]:
np.median(arr)

49.5

In [48]:
arr.max(axis=0)

99

In [49]:
arr = np.random.random((15,16))

In [50]:
arr

array([[0.23151352, 0.13506774, 0.79770042, 0.70738425, 0.2642011 ,
        0.84707268, 0.23685715, 0.78683763, 0.48016251, 0.01018322,
        0.62895905, 0.96836606, 0.28964173, 0.19888438, 0.93183684,
        0.8089435 ],
       [0.04473304, 0.36916349, 0.60096066, 0.71861659, 0.78688414,
        0.77592398, 0.96872006, 0.15059769, 0.64558571, 0.83160883,
        0.03410333, 0.66832635, 0.73994865, 0.86315744, 0.9681578 ,
        0.82300284],
       [0.04257596, 0.37703545, 0.19697199, 0.18751386, 0.18469169,
        0.81662941, 0.83669573, 0.79174673, 0.58829872, 0.54063257,
        0.04782875, 0.66868708, 0.22342524, 0.59372381, 0.09511455,
        0.78352816],
       [0.42241951, 0.15824505, 0.143409  , 0.63288505, 0.55491245,
        0.62694881, 0.10820852, 0.11724226, 0.70005751, 0.20119876,
        0.97671542, 0.79732545, 0.03419991, 0.29661935, 0.59054066,
        0.16634856],
       [0.63632269, 0.0037828 , 0.04929526, 0.09886975, 0.77526972,
        0.00385277, 0.86311224, 

In [51]:
arr.max(axis = 0)

array([0.90384552, 0.88702265, 0.98796674, 0.77307552, 0.78688414,
       0.97254157, 0.96872006, 0.79174673, 0.96793254, 0.91621298,
       0.99020684, 0.97495545, 0.87368256, 0.92442393, 0.9681578 ,
       0.97573264])

In [52]:
arr.max(axis = 1)

array([0.96836606, 0.96872006, 0.83669573, 0.97671542, 0.87368256,
       0.94141325, 0.79194147, 0.97573264, 0.97495545, 0.92285027,
       0.9307998 , 0.92442393, 0.99020684, 0.98796674, 0.97254157])

In [53]:
arr.reshape(16,15)

array([[0.23151352, 0.13506774, 0.79770042, 0.70738425, 0.2642011 ,
        0.84707268, 0.23685715, 0.78683763, 0.48016251, 0.01018322,
        0.62895905, 0.96836606, 0.28964173, 0.19888438, 0.93183684],
       [0.8089435 , 0.04473304, 0.36916349, 0.60096066, 0.71861659,
        0.78688414, 0.77592398, 0.96872006, 0.15059769, 0.64558571,
        0.83160883, 0.03410333, 0.66832635, 0.73994865, 0.86315744],
       [0.9681578 , 0.82300284, 0.04257596, 0.37703545, 0.19697199,
        0.18751386, 0.18469169, 0.81662941, 0.83669573, 0.79174673,
        0.58829872, 0.54063257, 0.04782875, 0.66868708, 0.22342524],
       [0.59372381, 0.09511455, 0.78352816, 0.42241951, 0.15824505,
        0.143409  , 0.63288505, 0.55491245, 0.62694881, 0.10820852,
        0.11724226, 0.70005751, 0.20119876, 0.97671542, 0.79732545],
       [0.03419991, 0.29661935, 0.59054066, 0.16634856, 0.63632269,
        0.0037828 , 0.04929526, 0.09886975, 0.77526972, 0.00385277,
        0.86311224, 0.13167354, 0.24219286, 

In [54]:
#this function is non destructive


In [55]:
arr[:,2]

array([0.79770042, 0.60096066, 0.19697199, 0.143409  , 0.04929526,
       0.54874808, 0.1495555 , 0.44811986, 0.2879027 , 0.66022926,
       0.39727505, 0.86455075, 0.75873608, 0.98796674, 0.80651115])

In [56]:
arr[2,:]

array([0.04257596, 0.37703545, 0.19697199, 0.18751386, 0.18469169,
       0.81662941, 0.83669573, 0.79174673, 0.58829872, 0.54063257,
       0.04782875, 0.66868708, 0.22342524, 0.59372381, 0.09511455,
       0.78352816])

In [57]:
arr[2:4,:]

array([[0.04257596, 0.37703545, 0.19697199, 0.18751386, 0.18469169,
        0.81662941, 0.83669573, 0.79174673, 0.58829872, 0.54063257,
        0.04782875, 0.66868708, 0.22342524, 0.59372381, 0.09511455,
        0.78352816],
       [0.42241951, 0.15824505, 0.143409  , 0.63288505, 0.55491245,
        0.62694881, 0.10820852, 0.11724226, 0.70005751, 0.20119876,
        0.97671542, 0.79732545, 0.03419991, 0.29661935, 0.59054066,
        0.16634856]])

In [59]:

arr[2:4,1:2]

array([[0.37703545],
       [0.15824505]])

In [60]:
arr.transpose()

array([[0.23151352, 0.04473304, 0.04257596, 0.42241951, 0.63632269,
        0.61500376, 0.6099773 , 0.03904531, 0.79831152, 0.25729715,
        0.90384552, 0.28680976, 0.47641189, 0.14877878, 0.16354492],
       [0.13506774, 0.36916349, 0.37703545, 0.15824505, 0.0037828 ,
        0.6049733 , 0.79194147, 0.07379139, 0.09889946, 0.4151912 ,
        0.44793802, 0.88702265, 0.49386796, 0.45275633, 0.77754222],
       [0.79770042, 0.60096066, 0.19697199, 0.143409  , 0.04929526,
        0.54874808, 0.1495555 , 0.44811986, 0.2879027 , 0.66022926,
        0.39727505, 0.86455075, 0.75873608, 0.98796674, 0.80651115],
       [0.70738425, 0.71861659, 0.18751386, 0.63288505, 0.09886975,
        0.61069573, 0.23561105, 0.77307552, 0.51497718, 0.19373508,
        0.39631763, 0.12500072, 0.40045242, 0.45063035, 0.17372863],
       [0.2642011 , 0.78688414, 0.18469169, 0.55491245, 0.77526972,
        0.68917352, 0.58126271, 0.45085429, 0.20227553, 0.05267692,
        0.17346393, 0.30551225, 0.29438931, 

In [61]:
np.vsplit(arr,12)

ValueError: array split does not result in an equal division

In [62]:
np.vsplit(arr,3)

[array([[0.23151352, 0.13506774, 0.79770042, 0.70738425, 0.2642011 ,
         0.84707268, 0.23685715, 0.78683763, 0.48016251, 0.01018322,
         0.62895905, 0.96836606, 0.28964173, 0.19888438, 0.93183684,
         0.8089435 ],
        [0.04473304, 0.36916349, 0.60096066, 0.71861659, 0.78688414,
         0.77592398, 0.96872006, 0.15059769, 0.64558571, 0.83160883,
         0.03410333, 0.66832635, 0.73994865, 0.86315744, 0.9681578 ,
         0.82300284],
        [0.04257596, 0.37703545, 0.19697199, 0.18751386, 0.18469169,
         0.81662941, 0.83669573, 0.79174673, 0.58829872, 0.54063257,
         0.04782875, 0.66868708, 0.22342524, 0.59372381, 0.09511455,
         0.78352816],
        [0.42241951, 0.15824505, 0.143409  , 0.63288505, 0.55491245,
         0.62694881, 0.10820852, 0.11724226, 0.70005751, 0.20119876,
         0.97671542, 0.79732545, 0.03419991, 0.29661935, 0.59054066,
         0.16634856],
        [0.63632269, 0.0037828 , 0.04929526, 0.09886975, 0.77526972,
         0.0038

In [65]:
np.hsplit(arr,2)

[array([[0.23151352, 0.13506774, 0.79770042, 0.70738425, 0.2642011 ,
         0.84707268, 0.23685715, 0.78683763],
        [0.04473304, 0.36916349, 0.60096066, 0.71861659, 0.78688414,
         0.77592398, 0.96872006, 0.15059769],
        [0.04257596, 0.37703545, 0.19697199, 0.18751386, 0.18469169,
         0.81662941, 0.83669573, 0.79174673],
        [0.42241951, 0.15824505, 0.143409  , 0.63288505, 0.55491245,
         0.62694881, 0.10820852, 0.11724226],
        [0.63632269, 0.0037828 , 0.04929526, 0.09886975, 0.77526972,
         0.00385277, 0.86311224, 0.13167354],
        [0.61500376, 0.6049733 , 0.54874808, 0.61069573, 0.68917352,
         0.94141325, 0.55341667, 0.22957457],
        [0.6099773 , 0.79194147, 0.1495555 , 0.23561105, 0.58126271,
         0.22366632, 0.56289113, 0.14984422],
        [0.03904531, 0.07379139, 0.44811986, 0.77307552, 0.45085429,
         0.285142  , 0.20346123, 0.74328223],
        [0.79831152, 0.09889946, 0.2879027 , 0.51497718, 0.20227553,
         0.

In [67]:
np.hstack((arr,l))

ValueError: all the input arrays must have same number of dimensions

In [68]:
arr1.copy(arr)

D:\Conda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  """Entry point for launching an IPython kernel.


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [69]:
arr1 = arr.copy()

In [70]:
np.hstack((arr,arr1))

array([[0.23151352, 0.13506774, 0.79770042, 0.70738425, 0.2642011 ,
        0.84707268, 0.23685715, 0.78683763, 0.48016251, 0.01018322,
        0.62895905, 0.96836606, 0.28964173, 0.19888438, 0.93183684,
        0.8089435 , 0.23151352, 0.13506774, 0.79770042, 0.70738425,
        0.2642011 , 0.84707268, 0.23685715, 0.78683763, 0.48016251,
        0.01018322, 0.62895905, 0.96836606, 0.28964173, 0.19888438,
        0.93183684, 0.8089435 ],
       [0.04473304, 0.36916349, 0.60096066, 0.71861659, 0.78688414,
        0.77592398, 0.96872006, 0.15059769, 0.64558571, 0.83160883,
        0.03410333, 0.66832635, 0.73994865, 0.86315744, 0.9681578 ,
        0.82300284, 0.04473304, 0.36916349, 0.60096066, 0.71861659,
        0.78688414, 0.77592398, 0.96872006, 0.15059769, 0.64558571,
        0.83160883, 0.03410333, 0.66832635, 0.73994865, 0.86315744,
        0.9681578 , 0.82300284],
       [0.04257596, 0.37703545, 0.19697199, 0.18751386, 0.18469169,
        0.81662941, 0.83669573, 0.79174673, 0.5882

In [71]:
arr>0.3

array([[False, False,  True,  True, False,  True, False,  True,  True,
        False,  True,  True, False, False,  True,  True],
       [False,  True,  True,  True,  True,  True,  True, False,  True,
         True, False,  True,  True,  True,  True,  True],
       [False,  True, False, False, False,  True,  True,  True,  True,
         True, False,  True, False,  True, False,  True],
       [ True, False, False,  True,  True,  True, False, False,  True,
        False,  True,  True, False, False,  True, False],
       [ True, False, False, False,  True, False,  True, False, False,
        False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False,  True, False],
       [ True,  True, False, False,  True, False,  True, False,  True,
        False, False,  True,  True, False, False, False],
       [False, False,  True,  True,  True, False, False,  True, False,
         True,  True,  Tru

In [72]:
arr[arr>0.3]

array([0.79770042, 0.70738425, 0.84707268, 0.78683763, 0.48016251,
       0.62895905, 0.96836606, 0.93183684, 0.8089435 , 0.36916349,
       0.60096066, 0.71861659, 0.78688414, 0.77592398, 0.96872006,
       0.64558571, 0.83160883, 0.66832635, 0.73994865, 0.86315744,
       0.9681578 , 0.82300284, 0.37703545, 0.81662941, 0.83669573,
       0.79174673, 0.58829872, 0.54063257, 0.66868708, 0.59372381,
       0.78352816, 0.42241951, 0.63288505, 0.55491245, 0.62694881,
       0.70005751, 0.97671542, 0.79732545, 0.59054066, 0.63632269,
       0.77526972, 0.86311224, 0.73085367, 0.41413358, 0.87368256,
       0.63444299, 0.60400472, 0.40494736, 0.61500376, 0.6049733 ,
       0.54874808, 0.61069573, 0.68917352, 0.94141325, 0.55341667,
       0.36785496, 0.43432861, 0.8944852 , 0.64107586, 0.65940092,
       0.58893641, 0.6099773 , 0.79194147, 0.58126271, 0.56289113,
       0.39240898, 0.35490528, 0.36760005, 0.44811986, 0.77307552,
       0.45085429, 0.74328223, 0.43838548, 0.53003406, 0.44962

In [87]:
#TASK 1 ARRAYS 

input = [12,3,4,2,14,5,11]
input = input[::-1]
arr = np.array(input).astype(float)
print(arr)

[11.  5. 14.  2.  4.  3. 12.]


In [80]:
type(arr)

numpy.ndarray

In [85]:
arr.itemsize

4

In [86]:
arr

array([11,  5, 14,  2,  4,  3, 12])

In [88]:
arr = np.array([[2,3,4],[5,4,2],[4,6,7]])

In [89]:
arr

array([[2, 3, 4],
       [5, 4, 2],
       [4, 6, 7]])

In [91]:
arr.min(axis = 1).max()

4